apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
            - containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
          env:
            - name: VAULT_ADDR
              value: {{ .Values.env.VAULT_ADDR | quote }}
            - name: VAULT_TOKEN
              value: {{ .Values.env.VAULT_TOKEN | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
