apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
    - port: 8081
      targetPort: {{ .Values.service.adminPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Chart.Name }}
