name: "OpenSSF Scorecard Supply-Chain Validation"
on:
  branch_protection_rule:
  schedule:
    - cron: '30 2 * * 3'
  push:
    branches: [ "main" ]
permissions: read-all
jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@e93faf2ab2f3663b51bc6e62d42b8520f2eff874 # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload artifact natively"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: "Upload SARIF telemetry to GitHub code-scanning dashboard"
        uses: github/codeql-action/upload-sarif@38b3b7bf288d49ccf58644769dc7a6afdccd05eb # v3
        with:
          sarif_file: results.sarif
